"""add price snapshot to notes

Revision ID: b0528917ab2d
Revises: 80631f576287
Create Date: 2026-06-29 16:40:32.889054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0528917ab2d'
down_revision: Union[str, Sequence[str], None] = '80631f576287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_notes', sa.Column('price_at_creation', sa.Float(), nullable=True))
    op.add_column('research_notes', sa.Column('currency', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_notes', 'currency')
    op.drop_column('research_notes', 'price_at_creation')
    # ### end Alembic commands ###
